"""Initial permission catalog, seeded by migration; runtime grants are read from DB."""

ROLE_PERMISSIONS = {
    "PLATFORM_ADMIN": ["organizations.manage", "finance.view"],
    "ORG_ADMIN": [
        "users.manage",
        "roles.manage",
        "events.create",
        "events.update",
        "events.delete",
        "events.manage",
        "tickets.manage",
        "tickets.scan",
        "tickets.checkin",
        "announcements.create",
        "announcements.update",
        "announcements.publish",
        "announcements.manage",
        "products.manage",
        "inventory.manage",
        "fundraisers.manage",
        "tasks.create",
        "tasks.assign",
        "tasks.update_own",
        "expenses.submit",
        "expenses.approve",
        "expenses.reimburse",
        "finance.view",
        "finance.manage",
        "orders.purchase",
        "orders.view_own",
        "membership.view_own",
        "membership.purchase",
    ],
    "TREASURER": [
        "expenses.submit",
        "expenses.approve",
        "expenses.reimburse",
        "finance.view",
        "finance.manage",
        "orders.purchase",
        "orders.view_own",
        "membership.view_own",
        "membership.purchase",
    ],
    "EVENT_MANAGER": [
        "events.create",
        "events.update",
        "events.delete",
        "events.manage",
        "tickets.manage",
        "tickets.scan",
        "tickets.checkin",
        "announcements.create",
        "announcements.update",
        "announcements.publish",
        "announcements.manage",
        "products.manage",
        "inventory.manage",
        "fundraisers.manage",
        "tasks.create",
        "tasks.assign",
        "tasks.update_own",
        "expenses.submit",
        "finance.view",
        "finance.read_only",
        "orders.purchase",
        "orders.view_own",
        "membership.view_own",
        "membership.purchase",
    ],
    "GATE_STAFF": [
        "tickets.scan",
        "tickets.checkin",
        "orders.purchase",
        "orders.view_own",
        "membership.view_own",
        "membership.purchase",
    ],
    "VOLUNTEER": [
        "tasks.update_own",
        "expenses.submit",
        "orders.purchase",
        "orders.view_own",
        "membership.view_own",
        "membership.purchase",
    ],
}
BASE_PERMISSIONS = [
    "orders.purchase",
    "orders.view_own",
    "membership.view_own",
    "membership.purchase",
]
