"""Organization access, scoped staff roles and audit trail."""

import sqlalchemy as sa
from alembic import op

revision = "0003_access"
down_revision = "0002_sessions"
branch_labels = None
depends_on = None

# Frozen initial catalog; later changes need their own migration.
CATALOG = {
    "PLATFORM_ADMIN": ["organizations.manage", "finance.view"],
    "ORG_ADMIN": [
        "users.manage",
        "roles.manage",
        "events.create",
        "events.update",
        "events.delete",
        "events.manage",
        "tickets.manage",
        "tickets.scan",
        "tickets.checkin",
        "announcements.create",
        "announcements.update",
        "announcements.publish",
        "announcements.manage",
        "products.manage",
        "inventory.manage",
        "fundraisers.manage",
        "tasks.create",
        "tasks.assign",
        "tasks.update_own",
        "expenses.submit",
        "expenses.approve",
        "expenses.reimburse",
        "finance.view",
        "finance.manage",
        "orders.purchase",
        "orders.view_own",
        "membership.view_own",
        "membership.purchase",
    ],
    "TREASURER": [
        "expenses.submit",
        "expenses.approve",
        "expenses.reimburse",
        "finance.view",
        "finance.manage",
        "orders.purchase",
        "orders.view_own",
        "membership.view_own",
        "membership.purchase",
    ],
    "EVENT_MANAGER": [
        "events.create",
        "events.update",
        "events.delete",
        "events.manage",
        "tickets.manage",
        "tickets.scan",
        "tickets.checkin",
        "announcements.create",
        "announcements.update",
        "announcements.publish",
        "announcements.manage",
        "products.manage",
        "inventory.manage",
        "fundraisers.manage",
        "tasks.create",
        "tasks.assign",
        "tasks.update_own",
        "expenses.submit",
        "finance.view",
        "finance.read_only",
        "orders.purchase",
        "orders.view_own",
        "membership.view_own",
        "membership.purchase",
    ],
    "GATE_STAFF": [
        "tickets.scan",
        "tickets.checkin",
        "orders.purchase",
        "orders.view_own",
        "membership.view_own",
        "membership.purchase",
    ],
    "VOLUNTEER": [
        "tasks.update_own",
        "expenses.submit",
        "orders.purchase",
        "orders.view_own",
        "membership.view_own",
        "membership.purchase",
    ],
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("join_code", sa.String(length=32), nullable=False),
        sa.Column("member_number_prefix", sa.String(length=12), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'SUSPENDED')", name=op.f("ck_organizations_valid_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("join_code", name=op.f("uq_organizations_join_code")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.create_table(
        "permissions",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_permissions")),
    )
    op.create_table(
        "roles",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_roles")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_logs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        op.f("ix_audit_logs_organization_id"), "audit_logs", ["organization_id"], unique=False
    )
    op.create_table(
        "organization_terms",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("ends_on >= starts_on", name=op.f("ck_organization_terms_valid_dates")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_terms_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_terms")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_organization_terms_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_organization_terms_organization_id"),
        "organization_terms",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "organization_users",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'SUSPENDED')", name=op.f("ck_organization_users_valid_status")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_users_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_organization_users_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_users")),
        sa.UniqueConstraint(
            "organization_id", "student_id", name=op.f("uq_organization_users_organization_id")
        ),
        sa.UniqueConstraint(
            "organization_id", "user_id", name=op.f("uq_organization_users_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_organization_users_organization_id"),
        "organization_users",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_users_user_id"), "organization_users", ["user_id"], unique=False
    )
    op.create_table(
        "platform_admins",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_platform_admins_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_platform_admins")),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_code", sa.String(length=32), nullable=False),
        sa.Column("permission_code", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_code"],
            ["permissions.code"],
            name=op.f("fk_role_permissions_permission_code_permissions"),
        ),
        sa.ForeignKeyConstraint(
            ["role_code"], ["roles.code"], name=op.f("fk_role_permissions_role_code_roles")
        ),
        sa.PrimaryKeyConstraint("role_code", "permission_code", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "organization_invitations",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role_code", sa.String(length=32), nullable=False),
        sa.Column("term_id", sa.Uuid(), nullable=True),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(role_code = 'ORG_ADMIN' AND term_id IS NULL) OR "
            "(role_code <> 'ORG_ADMIN' AND term_id IS NOT NULL)",
            name=op.f("ck_organization_invitations_term_scope"),
        ),
        sa.CheckConstraint(
            "role_code IN ('ORG_ADMIN', 'TREASURER', 'EVENT_MANAGER', 'GATE_STAFF', 'VOLUNTEER')",
            name=op.f("ck_organization_invitations_staff_only"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "term_id"],
            ["organization_terms.organization_id", "organization_terms.id"],
            name=op.f("fk_organization_invitations_organization_id_organization_terms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_invitations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_code"], ["roles.code"], name=op.f("fk_organization_invitations_role_code_roles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_organization_invitations_token_hash")),
    )
    op.create_index(
        op.f("ix_organization_invitations_email"),
        "organization_invitations",
        ["email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_invitations_organization_id"),
        "organization_invitations",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "organization_roles",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_code", sa.String(length=32), nullable=False),
        sa.Column("term_id", sa.Uuid(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(role_code = 'ORG_ADMIN' AND term_id IS NULL) OR "
            "(role_code <> 'ORG_ADMIN' AND term_id IS NOT NULL)",
            name=op.f("ck_organization_roles_term_scope"),
        ),
        sa.CheckConstraint(
            "role_code IN ('ORG_ADMIN', 'TREASURER', 'EVENT_MANAGER', 'GATE_STAFF', 'VOLUNTEER')",
            name=op.f("ck_organization_roles_staff_only"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "term_id"],
            ["organization_terms.organization_id", "organization_terms.id"],
            name=op.f("fk_organization_roles_organization_id_organization_terms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "user_id"],
            ["organization_users.organization_id", "organization_users.user_id"],
            name=op.f("fk_organization_roles_organization_id_organization_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_code"], ["roles.code"], name=op.f("fk_organization_roles_role_code_roles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_roles")),
        sa.UniqueConstraint(
            "organization_id",
            "user_id",
            "role_code",
            "term_id",
            name=op.f("uq_organization_roles_organization_id"),
        ),
    )
    op.create_index(
        op.f("ix_organization_roles_organization_id"),
        "organization_roles",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_roles_user_id"), "organization_roles", ["user_id"], unique=False
    )
    op.create_table(
        "session_organizations",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_session_organizations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["auth_sessions.id"],
            name=op.f("fk_session_organizations_session_id_auth_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_session_organizations")),
    )
    # ### end Alembic commands ###
    op.create_index(
        "uq_organization_terms_current",
        "organization_terms",
        ["organization_id"],
        unique=True,
        postgresql_where=sa.text("is_current = true"),
        sqlite_where=sa.text("is_current = 1"),
    )
    op.create_index(
        "uq_organization_roles_admin",
        "organization_roles",
        ["organization_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("term_id IS NULL"),
        sqlite_where=sa.text("term_id IS NULL"),
    )
    roles = sa.table("roles", sa.column("code", sa.String()))
    permissions = sa.table("permissions", sa.column("code", sa.String()))
    grants = sa.table(
        "role_permissions",
        sa.column("role_code", sa.String()),
        sa.column("permission_code", sa.String()),
    )
    op.bulk_insert(roles, [{"code": code} for code in CATALOG])
    op.bulk_insert(
        permissions,
        [{"code": code} for code in sorted({p for values in CATALOG.values() for p in values})],
    )
    op.bulk_insert(
        grants,
        [
            {"role_code": role, "permission_code": permission}
            for role, values in CATALOG.items()
            for permission in values
        ],
    )


def downgrade():
    op.drop_index("uq_organization_roles_admin", table_name="organization_roles")
    op.drop_index("uq_organization_terms_current", table_name="organization_terms")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session_organizations")
    op.drop_index(op.f("ix_organization_roles_user_id"), table_name="organization_roles")
    op.drop_index(op.f("ix_organization_roles_organization_id"), table_name="organization_roles")
    op.drop_table("organization_roles")
    op.drop_index(
        op.f("ix_organization_invitations_organization_id"), table_name="organization_invitations"
    )
    op.drop_index(op.f("ix_organization_invitations_email"), table_name="organization_invitations")
    op.drop_table("organization_invitations")
    op.drop_table("role_permissions")
    op.drop_table("platform_admins")
    op.drop_index(op.f("ix_organization_users_user_id"), table_name="organization_users")
    op.drop_index(op.f("ix_organization_users_organization_id"), table_name="organization_users")
    op.drop_table("organization_users")
    op.drop_index(op.f("ix_organization_terms_organization_id"), table_name="organization_terms")
    op.drop_table("organization_terms")
    op.drop_index(op.f("ix_audit_logs_organization_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("roles")
    op.drop_table("permissions")
    op.drop_table("organizations")
    # ### end Alembic commands ###
